services:
  - type: web
    name: mangetout
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: APP_BASE_URL
        sync: false
