# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mangetoutdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mangetout}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mangetout}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.h2.console.enabled=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
